name: Playwright Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Actualizado a v3 que usa Node.js 20

      - name: Set up Node.js
        uses: actions/setup-node@v3  # Asegúrate de que esta versión usa Node.js 20
        with:
          node-version: '22.1.0'

      - name: Install dependencies
        run: npm install

      - name: Set up environment variables
        run: echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> $GITHUB_ENV
        run: echo "API_KEY=${{ secrets.API_KEY }}" >> $GITHUB_ENV

      - name: Start server
        run: npm start &
        env:
          CI: true

      - name: Wait for server to be ready
        run: npx wait-on http://localhost:4000

      - name: Run Playwright tests
        run: npm test
        env:
          CI: true

      - name: Upload Playwright report
        uses: actions/upload-artifact@v3  # Actualizado a v3
        with:
          name: playwright-report
          path: playwright-report
